### ISSUE TITLE
Tutorial remains in the game

### ISSUE THREAD

**Issue by Can202** [dannygaray60/toziuha-night-oota#2]
When you return to this zone, the tutorial remains in the game.

if in the future you need to return to this room, you will see the tutorial again

![Toziuha Night - Order of the Alchemists (DEBUG) 16-05-2021 0_13_02](https://user-images.githubusercontent.com/67566612/118385277-ab387000-b5db-11eb-94f7-011d6787d89a.png)

**Comment by Can202** [comment]
postscript: the demo is very good, I loved it

**Comment by dannygaray60** [comment]
I know about that problem, this will be fixed in a final version of level tutorial, thanks for your report!!!!
